# Dependencies
markdown:         kramdown
kramdown:
  extensions: ["tables"]

highlighter:         rouge

# Permalinks
permalink:        pretty

# Setup
title:            Notes discrètes
tagline:          'Blog'
url:              http://notes-discretes.github.io
shorturl:         notes-discretes.github.io

author:
  name:           ''

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           github.com/notes-discretes/notes-discretes.github.io

# This is the list of pages to include in the header of the website.
pages_list:
  About: '/about/'
  Archive: '/archive/'

# Allow URL Redirects:
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
  - jekyll-paginate

#RSS
name: Semidoc	
description: Blog du séminaire des doctorants de l’IRIF à l’université Paris Diderot.
url: https://semidoc.github.io/
